#!/bin/bash

# ========================
# HOMEBREW
# ========================
echo "Installing homebrew and specified packages"

bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

brew install fasd \
  fzf \
  git \
  git-delta \
  lazygit \
  neovim \
  pure \
  ripgrep \
  zsh

brew install --cask amethyst \
  kitty

# ========================
# ZSH
# ========================
echo "Installing zsh and plugins"

sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions

# ========================
# POWERLINE FONTS
# ========================
echo "Installing powerline fonts"

git clone https://github.com/powerline/fonts.git --depth=1

cd fonts

./install.sh

cd ..

rm -rf fonts

# ========================
# CONFIG
# ========================
echo "Copying config files"

# zsh
cp ~/dotfiles/.zshrc ~/.zshrc

# git
cp ~/dotfiles/.gitconfig ~/.gitconfig

# neovim
cp ~/dotfiles/init.vim ~/.config/nvim/init.vim

# lazygit
cp ~/dotfiles/config.yml ~/Library/Application\ Support/lazygit/config.yml

# kitty
cp ~/dotfiles/kitty.conf ~/.config/kitty/kitty.conf
cp ~/dotfiles/gruvbox_dark.conf ~/.config/kitty/gruvbox_dark.conf

echo "Finished setup!"

