#!/bin/bash

# NOTE: Install Homebrew, oh-my-zsh, and fasd manually first
# Homebrew:
# /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
# oh-my-zsh:
# sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
# fasd:
# https://github.com/whjvenyl/fasd

# ========================
# HOMEBREW
# ========================
echo "Installing homebrew packages"

brew install bat \
  fd \
  fzf \
  git \
  git-delta \
  lazygit \
  neovim \
  node \
  pure \
  pyenv \
  ripgrep \
  zsh

brew install --cask amethyst \
  font-meslo-lg-nerd-font \
  kitty \
  raycast 

# ========================
# ZSH
# ========================
echo "Installing zsh plugins"

git clone https://github.com/zsh-users/zsh-autosuggestions ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
git clone https://github.com/davidparsson/zsh-pyenv-lazy.git ~/.oh-my-zsh/custom/plugins/pyenv-lazy

# ========================
# CONFIG
# ========================
echo "Copying config files"

# zsh
cp ~/dotfiles/.zshrc ~/.zshrc

# git
cp ~/dotfiles/.gitconfig ~/.gitconfig

# neovim
mkdir -p ~/.config/nvim
cp -R ~/dotfiles/nvim/ ~/.config/nvim/

# lazygit
mkdir -p ~/Library/Application\ Support/lazygit
cp ~/dotfiles/lazygit/config.yml ~/Library/Application\ Support/lazygit/config.yml

# kitty
mkdir -p ~/.config/kitty
cp -R ~/dotfiles/kitty/ ~/.config/kitty/

echo "Finished setup!"
