#!/bin/bash

# ========================
# HOMEBREW
# ========================
echo "Installing homebrew and specified packages"

bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

brew install bat \
  fasd \
  fd \
  fzf \
  git \
  git-delta \
  lazygit \
  neovim \
  pure \
  pyenv \
  ripgrep \
  zsh

brew install --cask amethyst \
  font-meslo-lg-nerd-font \
  kitty \
  raycast 

# ========================
# ZSH
# ========================
echo "Installing zsh and plugins"

sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
git clone https://github.com/davidparsson/zsh-pyenv-lazy.git ~/.oh-my-zsh/custom/plugins/pyenv-lazy

# ========================
# CONFIG
# ========================
echo "Copying config files"

# zsh
cp ~/dotfiles/.zshrc ~/.zshrc

# git
cp ~/dotfiles/.gitconfig ~/.gitconfig

# neovim
mkdir -p ~/.config/nvim
cp -R ~/dotfiles/nvim/ ~/.config/nvim/

# lazygit
mkdir -p ~/Library/Application\ Support/lazygit
cp ~/dotfiles/lazygit/config.yml ~/Library/Application\ Support/lazygit/config.yml

# kitty
mkdir -p ~/.config/kitty
cp -R ~/dotfiles/kitty/ ~/.config/kitty/

echo "Finished setup!"
