#!/bin/bash

cp ~/.vimrc ~/dev-config/vimrc
echo "Copied .vimrc file"

cp ~/.zshrc ~/dev-config/zshrc
echo "Copied .zshrc file"

cp ~/.vim/coc-settings.json ~/dev-config/coc-settings.json
echo "Copied coc-settings.json file"

cp ~/.gitconfig ~/dev-config/gitconfig
echo "Copied .gitconfig file"

echo "Finished update!"
