#!/bin/bash

cp ~/.gitconfig ~/dev-config/.gitconfig
echo "Copied .gitconfig file"

cp ~/.vimrc ~/dev-config/.vimrc
echo "Copied .vimrc file"

cp ~/.zshrc ~/dev-config/.zshrc
echo "Copied .zshrc file"

cp -R ~/.zsh ~/dev-config/.zsh
echo "Copied .zsh directory"

cp -R ~/.vim ~/dev-config/.vim
echo "Copied .vim directory"


