#!/bin/bash

# zsh
cp ~/.zshrc ~/dotfiles/.zshrc

# git
cp ~/.gitconfig ~/dotfiles/.gitconfig

# neovim
cp ~/.config/nvim/init.vim ~/dotfiles/init.vim
cp ~/.config/nvim/coc-settings.json ~/dotfiles/coc-settings.json

echo "Finished update!"
