#!/bin/bash

cp ~/.gitconfig ~/dev-config/.gitconfig
echo "Copied .gitconfig file"

cp ~/.vimrc ~/dev-config/.vimrc
echo "Copied .vimrc file"

cp ~/.zshrc ~/dev-config/.zshrc
echo "Copied .zshrc file"

cp -R ~/.zsh ~/dev-config/.zsh
echo "Copied .zsh directory"

cp ~/.vim/coc-settings.json ~/dev-config/.vim/coc-settings.json
echo "Copied coc-settings.json file"

